import { part1, part2 } from "../src/day07";

describe("Day 7", () => {
    const exampleInput = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`;

    test("Part 1 Example", () => {
        expect(part1(exampleInput.trim())).toBe(21);
    });

    test("Part 2 Example", () => {
        expect(part2(exampleInput.trim())).toBe(40);
    });
});
